- name: Demon On Loops
  hosts: localhost
  tasks:
    - name: print a loop
      ansible.builtin.debug:
        msg: "Fruit Name - {{item}}"
      loop:
        - apple
        - orange
    - name: Loop on list of maps
      ansible.builtin.debug:
        msg: "Fruit Name - {{item.name}}, Count - {{item.count}}"
      loop:
        - {name: "apple", count: 100 }
        - {name: "orange", count: 50 }